In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
crop_data = pd.read_csv("../data/raw/ICRISAT-District Level Data.csv")
rainfall_data = pd.read_csv("../data/raw/rainfall in india 1901-2015.csv")

print("Crop dataset loaded")
print("Rainfall dataset loaded")

Crop dataset loaded
Rainfall dataset loaded

In [3]:
print("Crop Data Shape:", crop_data.shape)
print("Rainfall Data Shape:", rainfall_data.shape)

Crop Data Shape: (16146, 80)
Rainfall Data Shape: (4116, 19)

In [4]:
crop_data.columns

Index(['Dist Code', 'Year', 'State Code', 'State Name', 'Dist Name',
       'RICE AREA (1000 ha)', 'RICE PRODUCTION (1000 tons)',
       'RICE YIELD (Kg per ha)', 'WHEAT AREA (1000 ha)',
       'WHEAT PRODUCTION (1000 tons)', 'WHEAT YIELD (Kg per ha)',
       'KHARIF SORGHUM AREA (1000 ha)',
       'KHARIF SORGHUM PRODUCTION (1000 tons)',
       'KHARIF SORGHUM YIELD (Kg per ha)', 'RABI SORGHUM AREA (1000 ha)',
       'RABI SORGHUM PRODUCTION (1000 tons)', 'RABI SORGHUM YIELD (Kg per ha)',
       'SORGHUM AREA (1000 ha)', 'SORGHUM PRODUCTION (1000 tons)',
       'SORGHUM YIELD (Kg per ha)', 'PEARL MILLET AREA (1000 ha)',
       'PEARL MILLET PRODUCTION (1000 tons)', 'PEARL MILLET YIELD (Kg per ha)',
       'MAIZE AREA (1000 ha)', 'MAIZE PRODUCTION (1000 tons)',
       'MAIZE YIELD (Kg per ha)', 'FINGER MILLET AREA (1000 ha)',
       'FINGER MILLET PRODUCTION (1000 tons)',
       'FINGER MILLET YIELD (Kg per ha)', 'BARLEY AREA (1000 ha)',
       'BARLEY PRODUCTION (1000 tons)', 'BARLEY YIELD (Kg per ha)',
       'CHICKPEA AREA (1000 ha)', 'CHICKPEA PRODUCTION (1000 tons)',
       'CHICKPEA YIELD (Kg per ha)', 'PIGEONPEA AREA (1000 ha)',
       'PIGEONPEA PRODUCTION (1000 tons)', 'PIGEONPEA YIELD (Kg per ha)',
       'MINOR PULSES AREA (1000 ha)', 'MINOR PULSES PRODUCTION (1000 tons)',
       'MINOR PULSES YIELD (Kg per ha)', 'GROUNDNUT AREA (1000 ha)',
       'GROUNDNUT PRODUCTION (1000 tons)', 'GROUNDNUT YIELD (Kg per ha)',
       'SESAMUM AREA (1000 ha)', 'SESAMUM PRODUCTION (1000 tons)',
       'SESAMUM YIELD (Kg per ha)', 'RAPESEED AND MUSTARD AREA (1000 ha)',
       'RAPESEED AND MUSTARD PRODUCTION (1000 tons)',
       'RAPESEED AND MUSTARD YIELD (Kg per ha)', 'SAFFLOWER AREA (1000 ha)',
       'SAFFLOWER PRODUCTION (1000 tons)', 'SAFFLOWER YIELD (Kg per ha)',
       'CASTOR AREA (1000 ha)', 'CASTOR PRODUCTION (1000 tons)',
       'CASTOR YIELD (Kg per ha)', 'LINSEED AREA (1000 ha)',
       'LINSEED PRODUCTION (1000 tons)', 'LINSEED YIELD (Kg per ha)',
       'SUNFLOWER AREA (1000 ha)', 'SUNFLOWER PRODUCTION (1000 tons)',
       'SUNFLOWER YIELD (Kg per ha)', 'SOYABEAN AREA (1000 ha)',
       'SOYABEAN PRODUCTION (1000 tons)', 'SOYABEAN YIELD (Kg per ha)',
       'OILSEEDS AREA (1000 ha)', 'OILSEEDS PRODUCTION (1000 tons)',
       'OILSEEDS YIELD (Kg per ha)', 'SUGARCANE AREA (1000 ha)',
       'SUGARCANE PRODUCTION (1000 tons)', 'SUGARCANE YIELD (Kg per ha)',
       'COTTON AREA (1000 ha)', 'COTTON PRODUCTION (1000 tons)',
       'COTTON YIELD (Kg per ha)', 'FRUITS AREA (1000 ha)',
       'VEGETABLES AREA (1000 ha)', 'FRUITS AND VEGETABLES AREA (1000 ha)',
       'POTATOES AREA (1000 ha)', 'ONION AREA (1000 ha)',
       'FODDER AREA (1000 ha)'],
      dtype='object')

In [5]:
rainfall_data.columns

Index(['SUBDIVISION', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb', 'Mar-May',
       'Jun-Sep', 'Oct-Dec'],
      dtype='object')

In [6]:
crop_data.head()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,1966,14,Chhattisgarh,Durg,548.0,185.0,337.59,44.0,20.0,...,1777.78,0.0,0.0,0.0,5.95,6.64,12.59,0.01,0.60,0.47
1,1,1967,14,Chhattisgarh,Durg,547.0,409.0,747.71,50.0,26.0,...,1500.00,0.0,0.0,0.0,5.77,7.24,13.02,0.01,0.56,1.23
2,1,1968,14,Chhattisgarh,Durg,556.3,468.0,841.27,53.7,30.0,...,1000.00,0.0,0.0,0.0,5.41,7.40,12.81,0.10,0.58,1.02
3,1,1969,14,Chhattisgarh,Durg,563.4,400.8,711.40,49.4,26.5,...,1900.00,0.0,0.0,0.0,5.52,7.16,12.69,0.01,0.56,0.84
4,1,1970,14,Chhattisgarh,Durg,571.6,473.6,828.55,44.2,29.0,...,2000.00,0.0,0.0,0.0,5.45,7.19,12.64,0.02,0.52,0.42

In [7]:
wb_data = crop_data[crop_data['State Name'] == 'West Bengal']

wb_data.head()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
14500,800,1966,13,West Bengal,24 Parganas,603.36,628.09,1040.99,1.16,1.04,...,4200.00,0.0,0.0,0.0,5.26,26.63,31.89,3.20,-1.0,-1.0
14501,800,1967,13,West Bengal,24 Parganas,618.82,682.16,1102.36,2.29,1.98,...,3815.60,0.0,0.0,0.0,5.26,26.95,32.21,3.52,-1.0,-1.0
14502,800,1968,13,West Bengal,24 Parganas,615.70,703.49,1142.59,3.92,4.86,...,5021.16,0.0,0.0,0.0,29.02,28.61,57.63,3.00,-1.0,-1.0
14503,800,1969,13,West Bengal,24 Parganas,633.20,672.19,1061.58,5.43,6.19,...,5201.92,0.0,0.0,0.0,29.06,30.84,59.89,2.79,-1.0,-1.0
14504,800,1970,13,West Bengal,24 Parganas,582.40,475.70,816.79,9.09,11.27,...,4418.48,0.0,0.0,0.0,28.05,45.24,73.29,2.23,-1.0,0.0

In [8]:
rice_wb = wb_data[['Year',
                   'State Name',
                   'Dist Name',
                   'RICE AREA (1000 ha)',
                   'RICE PRODUCTION (1000 tons)',
                   'RICE YIELD (Kg per ha)']]

rice_wb.head()

,Year,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha)
14500,1966,West Bengal,24 Parganas,603.36,628.09,1040.99
14501,1967,West Bengal,24 Parganas,618.82,682.16,1102.36
14502,1968,West Bengal,24 Parganas,615.70,703.49,1142.59
14503,1969,West Bengal,24 Parganas,633.20,672.19,1061.58
14504,1970,West Bengal,24 Parganas,582.40,475.70,816.79

In [9]:
rice_wb = rice_wb.rename(columns={
    'Dist Name':'District',
    'RICE AREA (1000 ha)':'Area',
    'RICE PRODUCTION (1000 tons)':'Production',
    'RICE YIELD (Kg per ha)':'Yield'
})

rice_wb.head()

       Year   State Name     District    Area  Production    Yield
14500  1966  West Bengal  24 Parganas  603.36      628.09  1040.99
14501  1967  West Bengal  24 Parganas  618.82      682.16  1102.36
14502  1968  West Bengal  24 Parganas  615.70      703.49  1142.59
14503  1969  West Bengal  24 Parganas  633.20      672.19  1061.58
14504  1970  West Bengal  24 Parganas  582.40      475.70   816.79

In [10]:
rice_wb = rice_wb.dropna()

In [11]:
rice_wb.to_csv("../data/cleaned/rice_west_bengal_cleaned.csv", index=False)

print("Cleaned dataset saved")

Cleaned dataset saved

In [12]:
wb_rainfall = rainfall_data[rainfall_data['SUBDIVISION'] == 'Gangetic West Bengal']

wb_rainfall.head()

Empty DataFrame
Columns: [SUBDIVISION, YEAR, JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC, ANNUAL, Jan-Feb, Mar-May, Jun-Sep, Oct-Dec]
Index: []

In [13]:
wb_rainfall = wb_rainfall[['YEAR','ANNUAL']]

wb_rainfall = wb_rainfall.rename(columns={
    'YEAR':'Year',
    'ANNUAL':'Rainfall'
})

wb_rainfall.head()

Empty DataFrame
Columns: [Year, Rainfall]
Index: []

In [14]:
wb_rainfall.to_csv("../data/cleaned/west_bengal_rainfall.csv", index=False)

print("Rainfall dataset saved")

Rainfall dataset saved

In [15]:
rice_data = pd.read_csv("../data/cleaned/rice_west_bengal_cleaned.csv")
rainfall_data = pd.read_csv("../data/cleaned/west_bengal_rainfall.csv")

rice_data.head()

   Year   State Name     District    Area  Production    Yield
0  1966  West Bengal  24 Parganas  603.36      628.09  1040.99
1  1967  West Bengal  24 Parganas  618.82      682.16  1102.36
2  1968  West Bengal  24 Parganas  615.70      703.49  1142.59
3  1969  West Bengal  24 Parganas  633.20      672.19  1061.58
4  1970  West Bengal  24 Parganas  582.40      475.70   816.79

In [16]:
merged_data = pd.merge(rice_data, rainfall_data, on="Year", how="left")

merged_data.head()

   Year   State Name     District    Area  Production    Yield Rainfall
0  1966  West Bengal  24 Parganas  603.36      628.09  1040.99      NaN
1  1967  West Bengal  24 Parganas  618.82      682.16  1102.36      NaN
2  1968  West Bengal  24 Parganas  615.70      703.49  1142.59      NaN
3  1969  West Bengal  24 Parganas  633.20      672.19  1061.58      NaN
4  1970  West Bengal  24 Parganas  582.40      475.70   816.79      NaN

In [17]:
rice_data['Year'].min(), rice_data['Year'].max()

(1966, 2017)

In [18]:
rainfall_data['Year'].min(), rainfall_data['Year'].max()

(nan, nan)

In [19]:
wb_rainfall['Year'].min(), wb_rainfall['Year'].max()

(nan, nan)

In [20]:
rainfall_data['SUBDIVISION'].unique()

KeyError: 'SUBDIVISION'

In [ ]:
rainfall_data['SUBDIVISION']

In [ ]:
rainfall_data.columns

In [ ]:
rainfall_data = pd.read_csv("../data/raw/rainfall in india 1901-2015.csv")

In [ ]:
rainfall_data.columns

In [ ]:
wb_rainfall = rainfall_data[
    rainfall_data['SUBDIVISION'].isin([
        'Gangetic West Bengal',
        'Sub Himalayan West Bengal'
    ])
]

In [ ]:
wb_rainfall.head()

In [ ]:
wb_rainfall = wb_rainfall[['YEAR','ANNUAL']]

wb_rainfall = wb_rainfall.rename(columns={
    'YEAR':'Year',
    'ANNUAL':'Rainfall'
})

wb_rainfall.head()

In [ ]:
rainfall_data['SUBDIVISION'].unique()

In [ ]:
wb_rainfall = rainfall_data[
    rainfall_data['SUBDIVISION'].isin([
        'GANGETIC WEST BENGAL',
        'SUB HIMALAYAN WEST BENGAL & SIKKIM'
    ])
]

In [ ]:
wb_rainfall.head()

In [ ]:
wb_rainfall = wb_rainfall[['YEAR','ANNUAL']]

wb_rainfall = wb_rainfall.rename(columns={
    'YEAR':'Year',
    'ANNUAL':'Rainfall'
})

In [ ]:
wb_rainfall = wb_rainfall.groupby('Year')['Rainfall'].mean().reset_index()

In [ ]:
wb_rainfall.to_csv("../data/cleaned/west_bengal_rainfall.csv", index=False)

In [ ]:
rice_data = pd.read_csv("../data/cleaned/rice_west_bengal_cleaned.csv")

rainfall_data = pd.read_csv("../data/cleaned/west_bengal_rainfall.csv")

rice_data.head()

In [ ]:
rainfall_data.head()

In [ ]:
merged_data = pd.merge(rice_data, rainfall_data, on="Year", how="inner")

merged_data.head()

In [ ]:
merged_data.to_csv("../data/cleaned/final_dataset.csv", index=False)

In [ ]:
import matplotlib.pyplot as plt

# Plot
plt.figure()
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Yield")
plt.ylabel("Predicted Yield")
plt.title("Actual vs Predicted Yield")

# Save image
plt.savefig("yield_comparison.png")

# Show graph
plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# Example (adapt to your variables)
X = data[['Area', 'Production', 'Rainfall']]
y = data['Yield']

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
model = RandomForestRegressor()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)